
lastStatusChannelID: "212121"
lastStatusMessageID: "212121"

aircraft:
  - ZS-CCC:
      ICAO: B738
      status: Parked at FAOR
      lastStatusEditUserID: "21212121"
  - ZS-AAA:
      ICAO: C182
      status: Flying
      lastStatusEditUserID: "21212121"
