
lastStatusChannelID: "212121"
lastStatusMessageID: "212121"

aircraft:
  - ZS-CCC:
      ICAO: B738
      status: Parked at FAOR
      lastStatusEditUserID: "21212121"
      booking:
        booked: false
        callsign: null
        departureICAO: null
        arrivalICAO: null
        etd: null
        pilotUserID: null
  - ZS-AAA:
      ICAO: C182
      status: Flying
      lastStatusEditUserID: "21212121"
      booking:
        booked: false
        callsign: null
        departureICAO: null
        arrivalICAO: null
        etd: null
        pilotUserID: null
